[CmdletBinding()]
param(
	[string]$ArchivePath = "",
	[string]$GodotPath = ""
)

$ErrorActionPreference = "Stop"

$projectRoot = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
$pluginConfig = Join-Path $projectRoot "addons\easing_curve\plugin.cfg"
$runner = Join-Path $PSScriptRoot "run_godot.ps1"
$powerShellExecutable = (Get-Process -Id $PID).Path
$versionText = Get-Content -Raw -LiteralPath $pluginConfig
if ($versionText -notmatch '(?m)^\s*version\s*=\s*"([^"]+)"\s*$') {
	throw "Could not parse the plugin version."
}
$version = $Matches[1]
if ([string]::IsNullOrWhiteSpace($ArchivePath)) {
	$ArchivePath = Join-Path $projectRoot "_exports\_asset_store_builds\easing_curve_v$version.zip"
}
if (-not (Test-Path -LiteralPath $ArchivePath -PathType Leaf)) {
	throw "Release archive was not found: $ArchivePath"
}
$ArchivePath = (Resolve-Path -LiteralPath $ArchivePath).Path

$validationRoot = Join-Path $projectRoot ("test\_temp\release-archive-" + [guid]::NewGuid().ToString("N"))
$logDirectory = Join-Path $validationRoot "test\_temp"
$bootstrapLog = Join-Path $logDirectory "bootstrap.log"
$runtimeLog = Join-Path $logDirectory "runtime.log"
$succeeded = $false

function Invoke-Runner {
	param([string[]]$Arguments)
	$runnerArguments = @("-NoProfile", "-ExecutionPolicy", "Bypass", "-File", $runner)
	if (-not [string]::IsNullOrWhiteSpace($GodotPath)) {
		$runnerArguments += @("-GodotPath", $GodotPath)
	}
	$runnerArguments += $Arguments
	& $powerShellExecutable @runnerArguments | Out-Host
	$exitCode = $LASTEXITCODE
	return $exitCode
}

function Invoke-EditorLifecycle {
	param(
		[string]$Phase,
		[string]$LogPath
	)
	$exitCode = Invoke-Runner -Arguments @(
		"--editor", "--headless", "--path", $validationRoot, "--import", "--quit-after", "2",
		"--log-file", $LogPath
	)
	$logText = if (Test-Path -LiteralPath $LogPath) { Get-Content -Raw -LiteralPath $LogPath } else { "" }
	$classCache = Join-Path $validationRoot ".godot\global_script_class_cache.cfg"
	$failed = (-not (Test-Path -LiteralPath $classCache -PathType Leaf)) -or ($logText -match '(?m)^(?:SCRIPT ERROR:|.*Parse Error:|ERROR: Failed to load extension)')
	if ($failed) {
		throw "Exact-archive $Phase failed. Artifacts retained at $validationRoot"
	}
	if ($exitCode -ne 0) {
		Write-Warning "$Phase returned $exitCode after producing a clean class cache; continuing."
	}
}

try {
	New-Item -ItemType Directory -Force -Path $validationRoot, $logDirectory | Out-Null
	Expand-Archive -LiteralPath $ArchivePath -DestinationPath $validationRoot -Force
	$addonRoot = Join-Path $validationRoot "addons\easing_curve"
	$metadataPath = Join-Path $addonRoot "BUILD_METADATA.json"
	$checksumsPath = Join-Path $addonRoot "SHA256SUMS"
	if (-not (Test-Path -LiteralPath $metadataPath -PathType Leaf) -or -not (Test-Path -LiteralPath $checksumsPath -PathType Leaf)) {
		throw "The extracted archive is missing build metadata or checksums."
	}
	$metadata = Get-Content -Raw -LiteralPath $metadataPath | ConvertFrom-Json
	if ($metadata.version -ne $version -or $metadata.legacy_deprecated -ne $false) {
		throw "The archive metadata does not match the supported dual-API release contract."
	}
	foreach ($line in Get-Content -LiteralPath $checksumsPath) {
		if ($line -notmatch '^([0-9a-f]{64})\s{2}(.+)$') {
			throw "Malformed archive checksum line: $line"
		}
		$expectedHash = $Matches[1]
		$artifactPath = Join-Path $addonRoot $Matches[2].Replace('/', [IO.Path]::DirectorySeparatorChar)
		$actualHash = (Get-FileHash -Algorithm SHA256 -LiteralPath $artifactPath).Hash.ToLowerInvariant()
		if ($actualHash -cne $expectedHash) {
			throw "Archive checksum mismatch: $($Matches[2])"
		}
	}

	$projectConfig = @'
; Generated by test/runners/run_release_archive_test.ps1.
config_version=5

[application]
config/name="Easing Curve Exact Archive Validation"
config/features=PackedStringArray("4.7", "GL Compatibility")

[editor_plugins]
enabled=PackedStringArray("res://addons/easing_curve/plugin.cfg")

[rendering]
renderer/rendering_method="gl_compatibility"
renderer/rendering_method.mobile="gl_compatibility"
'@
	[IO.File]::WriteAllText((Join-Path $validationRoot "project.godot"), $projectConfig, [Text.UTF8Encoding]::new($false))
	[IO.File]::WriteAllText((Join-Path $logDirectory ".gdignore"), "", [Text.UTF8Encoding]::new($false))

	$runtimeScript = @'
extends SceneTree

func _init() -> void:
	var legacy_script := load("res://addons/easing_curve/scripts/runtime/easing_curve.gd")
	if legacy_script == null or not ClassDB.class_exists(&"NativeEasingCurve"):
		push_error("The exact archive did not load both curve APIs.")
		quit(1)
		return
	var legacy := legacy_script.new() as EasingCurve
	var native := ClassDB.instantiate(&"NativeEasingCurve") as Resource
	legacy.trans_type = EasingCurve.TRANS.BACK
	legacy.ease_type = EasingCurve.EASE.IN_OUT
	legacy.overshoot = 2.2
	native.set(&"transition", 10)
	native.set(&"ease_type", 2)
	native.set(&"overshoot", 2.2)
	for index in range(65):
		var offset := float(index) / 64.0
		if absf(legacy.sample(offset) - float(native.call(&"sample", offset))) > 0.00001:
			push_error("Mixed Legacy/Native sampling changed at %.6f." % offset)
			quit(1)
			return
	if ResourceSaver.save(legacy, "res://legacy_curve.tres") != OK:
		push_error("Could not save the extracted legacy resource.")
		quit(1)
		return
	if ResourceSaver.save(native, "res://native_curve.tres") != OK:
		push_error("Could not save the extracted Native resource.")
		quit(1)
		return
	var loaded_legacy := load("res://legacy_curve.tres") as EasingCurve
	var loaded_native := load("res://native_curve.tres") as Resource
	if loaded_legacy == null or loaded_native == null:
		push_error("Could not reload both extracted archive resources.")
		quit(1)
		return
	if not is_finite(loaded_legacy.sample(0.43)) or not is_finite(float(loaded_native.call(&"sample", 0.43))):
		push_error("A reloaded archive resource returned a non-finite sample.")
		quit(1)
		return
	print("PASS: exact archive loaded, sampled, saved, and reloaded both APIs")
	quit(0)
'@
	[IO.File]::WriteAllText((Join-Path $validationRoot "main.gd"), $runtimeScript, [Text.UTF8Encoding]::new($false))

	Invoke-EditorLifecycle -Phase "install/enable bootstrap" -LogPath $bootstrapLog

	$runtimeExit = Invoke-Runner -Arguments @(
		"--headless", "--path", $validationRoot, "--script", "res://main.gd",
		"--log-file", $runtimeLog
	)
	$runtimeText = if (Test-Path -LiteralPath $runtimeLog) { Get-Content -Raw -LiteralPath $runtimeLog } else { "" }
	if ($runtimeExit -ne 0 -or $runtimeText -notmatch '(?m)^PASS: exact archive loaded, sampled, saved, and reloaded both APIs$') {
		throw "Exact-archive runtime validation failed. Artifacts retained at $validationRoot"
	}

	$disabledConfig = $projectConfig.Replace(
		'enabled=PackedStringArray("res://addons/easing_curve/plugin.cfg")',
		'enabled=PackedStringArray()'
	)
	[IO.File]::WriteAllText((Join-Path $validationRoot "project.godot"), $disabledConfig, [Text.UTF8Encoding]::new($false))
	Invoke-EditorLifecycle -Phase "disable restart" -LogPath (Join-Path $logDirectory "disabled.log")
	[IO.File]::WriteAllText((Join-Path $validationRoot "project.godot"), $projectConfig, [Text.UTF8Encoding]::new($false))
	Invoke-EditorLifecycle -Phase "re-enable restart" -LogPath (Join-Path $logDirectory "reenabled.log")

	Write-Host "PASS: exact ZIP hashes, dual-API behavior, and plugin lifecycle validated."
	$succeeded = $true
}
finally {
	if ($succeeded -and (Test-Path -LiteralPath $validationRoot)) {
		Remove-Item -LiteralPath $validationRoot -Recurse -Force
	}
}
