[CmdletBinding()]
param(
    [ValidateSet("Current", "V109", "Both", "SequentialAB")]
    [string]$Mode = "Both",
    [string]$GodotPath = "",
    [ValidateSet("Auto", "None", "WPR")]
    [string]$Profiler = "Auto",
    [switch]$PrepareOnly,
    [switch]$SmokeTest,
    [switch]$KeepProjects
)

$ErrorActionPreference = "Stop"

function Resolve-ProjectRoot {
    $candidate = (Resolve-Path $PSScriptRoot).Path
    while ($true) {
        if (Test-Path -LiteralPath (Join-Path $candidate "project.godot") -PathType Leaf) {
            return $candidate
        }
        $parent = Split-Path -Parent $candidate
        if ([string]::IsNullOrWhiteSpace($parent) -or $parent -eq $candidate) {
            throw "Could not locate project.godot above runner directory: $PSScriptRoot"
        }
        $candidate = $parent
    }
}

function Resolve-GodotExecutables {
    param([string]$RequestedPath)

    $fallback = "C:\Godot\4.7\engine\Godot_v4.7.1-stable_win64.exe\Godot_v4.7.1-stable_win64.exe"
    $gui = $RequestedPath
    if ([string]::IsNullOrWhiteSpace($gui)) { $gui = $env:EASING_CURVE_GODOT_PATH }
    if ([string]::IsNullOrWhiteSpace($gui)) { $gui = $fallback }
    if (-not (Test-Path -LiteralPath $gui -PathType Leaf)) {
        throw "Godot executable was not found: $gui"
    }

    $gui = (Resolve-Path -LiteralPath $gui).Path
    if ([IO.Path]::GetFileNameWithoutExtension($gui).EndsWith("_console", [StringComparison]::OrdinalIgnoreCase)) {
        $candidate = $gui -replace '_console\.exe$', '.exe'
        if (Test-Path -LiteralPath $candidate -PathType Leaf) { $gui = $candidate }
    }

    $console = Join-Path ([IO.Path]::GetDirectoryName($gui)) ([IO.Path]::GetFileNameWithoutExtension($gui) + "_console.exe")
    if (-not (Test-Path -LiteralPath $console -PathType Leaf)) { $console = $gui }
    return @{ Gui = $gui; Console = $console }
}

function Write-ProjectConfig {
    param(
        [string]$Path,
        [string]$Label,
        [bool]$EnableProbe
    )

    $plugins = if ($EnableProbe) {
        'PackedStringArray("res://addons/easing_curve/plugin.cfg", "res://addons/easing_curve_physical_input_probe/plugin.cfg")'
    } else {
        'PackedStringArray("res://addons/easing_curve/plugin.cfg")'
    }

    $config = @"
; Generated by test/runners/run_physical_input_profile.ps1.
config_version=5

[application]
config/name="Easing Curve Physical Input - $Label"
config/features=PackedStringArray("4.7", "GL Compatibility")

[editor_plugins]
enabled=$plugins

[rendering]
renderer/rendering_method="gl_compatibility"
renderer/rendering_method.mobile="gl_compatibility"
"@
    [IO.File]::WriteAllText($Path, $config, [Text.UTF8Encoding]::new($false))
}

function Add-ProbeAddon {
    param([string]$ProjectPath)

    $probeAddon = Join-Path $ProjectPath "addons\easing_curve_physical_input_probe"
    New-Item -ItemType Directory -Force -Path $probeAddon | Out-Null
    Copy-Item `
        -LiteralPath (Join-Path $projectRoot "test\scripts\performance\easing_curve_physical_input_probe.gd") `
        -Destination (Join-Path $probeAddon "plugin.gd") `
        -Force

    $pluginConfig = @'
[plugin]
name="Easing Curve Physical Input Probe"
description="Temporary physical mouse delivery and frame-latency capture."
author="Easing Curve tests"
version="1.0"
script="plugin.gd"
'@
    [IO.File]::WriteAllText(
        (Join-Path $probeAddon "plugin.cfg"),
        $pluginConfig,
        [Text.UTF8Encoding]::new($false)
    )
}

function Get-PluginVersion {
    param([string]$ProjectPath)

    $pluginConfigPath = Join-Path $ProjectPath "addons\easing_curve\plugin.cfg"
    if (-not (Test-Path -LiteralPath $pluginConfigPath -PathType Leaf)) { return "unknown" }
    $text = Get-Content -Raw -LiteralPath $pluginConfigPath
    $match = [regex]::Match($text, '(?m)^version\s*=\s*"([^"]+)"')
    if ($match.Success) { return $match.Groups[1].Value }
    return "unknown"
}

function Test-LogHasScriptFailure {
    param([string]$Text)
    if ([string]::IsNullOrWhiteSpace($Text)) { return $false }
    return $Text -match '(?m)^(?:SCRIPT ERROR:|.*Parse Error:|ERROR: Failed to load script|ERROR: Failed loading resource:.*\.gd)'
}

function Prepare-ProfileProject {
    param(
        [string]$Label,
        [ValidateSet("current", "v109")]
        [string]$SourceKind
    )

    $projectPath = Join-Path $tempBase $Label
    if (Test-Path -LiteralPath $projectPath) {
        Remove-Item -LiteralPath $projectPath -Recurse -Force
    }
    New-Item -ItemType Directory -Force -Path $projectPath | Out-Null

    if ($SourceKind -eq "current") {
        New-Item -ItemType Directory -Force -Path (Join-Path $projectPath "addons") | Out-Null
        Copy-Item `
            -LiteralPath (Join-Path $projectRoot "addons\easing_curve") `
            -Destination (Join-Path $projectPath "addons\easing_curve") `
            -Recurse `
            -Force
    } else {
        $archive = Join-Path $tempBase ("easing_curve_" + $Label + ".zip")
        & git -C $projectRoot archive --format=zip --output=$archive v1.0.9 addons/easing_curve
        if ($LASTEXITCODE -ne 0) {
            throw "Could not archive v1.0.9 from the local repository."
        }
        Expand-Archive -LiteralPath $archive -DestinationPath $projectPath -Force
        Remove-Item -LiteralPath $archive -Force
    }

    Add-ProbeAddon -ProjectPath $projectPath

    $temp = Join-Path $projectPath "test\_temp"
    New-Item -ItemType Directory -Force -Path $temp | Out-Null
    [IO.File]::WriteAllText(
        (Join-Path $temp ".gdignore"),
        "",
        [Text.UTF8Encoding]::new($false)
    )

    $projectConfig = Join-Path $projectPath "project.godot"
    Write-ProjectConfig -Path $projectConfig -Label $Label -EnableProbe $false

    $bootstrapLog = Join-Path $temp "bootstrap.log"
    $bootstrapOutput = @(
        & $godot.Console --editor --headless --path $projectPath --import --log-file $bootstrapLog
    )
    $bootstrapExit = $LASTEXITCODE
    $cache = Join-Path $projectPath ".godot\global_script_class_cache.cfg"
    $bootstrapText = if (Test-Path -LiteralPath $bootstrapLog -PathType Leaf) {
        Get-Content -Raw -LiteralPath $bootstrapLog
    } else {
        ""
    }

    if (-not (Test-Path -LiteralPath $cache -PathType Leaf) -or (Test-LogHasScriptFailure $bootstrapText)) {
        if ($bootstrapOutput.Count -gt 0) {
            Write-Host ($bootstrapOutput -join [Environment]::NewLine)
        }
        throw "Profile project '$Label' failed bootstrap validation (exit $bootstrapExit). See $bootstrapLog"
    }

    Write-ProjectConfig -Path $projectConfig -Label $Label -EnableProbe $true

    $probeScript = Join-Path $projectPath "addons\easing_curve_physical_input_probe\plugin.gd"
    if (-not (Test-Path -LiteralPath $probeScript -PathType Leaf)) {
        throw "Profile project '$Label' is missing the physical-input probe."
    }

    return [string]$projectPath
}

function Get-WprPath {
    $command = Get-Command "wpr.exe" -ErrorAction SilentlyContinue
    if ($null -eq $command) { return "" }
    return [string]$command.Source
}

function Test-IsElevated {
    $identity = [Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = [Security.Principal.WindowsPrincipal]::new($identity)
    return $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

function Resolve-ProfilerMode {
    param([string]$RequestedProfiler)

    if ($RequestedProfiler -eq "None") { return "None" }
    if ($Mode -eq "Both") {
        if ($RequestedProfiler -eq "WPR") {
            throw "WPR capture is system-wide. Use -Mode SequentialAB -Profiler WPR from an elevated PowerShell for controlled A/B sampling. Use -Mode Both -Profiler None for side-by-side feel testing."
        }
        return "None"
    }

    $wpr = Get-WprPath
    if ($RequestedProfiler -eq "WPR") {
        if ([string]::IsNullOrWhiteSpace($wpr)) {
            throw "wpr.exe was not found. Install/enable Windows Performance Recorder or use -Profiler None."
        }
        if (-not (Test-IsElevated)) {
            throw "WPR CPU sampling requires the system-performance profiling privilege on this machine. Re-run this PowerShell as Administrator, or use -Profiler None."
        }
        return "WPR"
    }

    if (-not [string]::IsNullOrWhiteSpace($wpr) -and (Test-IsElevated)) {
        return "WPR"
    }
    if (-not [string]::IsNullOrWhiteSpace($wpr)) {
        Write-Warning "WPR is installed, but this PowerShell is not elevated. -Profiler Auto is falling back to None. Use an elevated shell with -Profiler WPR for sampled CPU stacks."
    }
    return "None"
}

function Start-WprCpuCapture {
    param([string]$Label)

    $wpr = Get-WprPath
    if ([string]::IsNullOrWhiteSpace($wpr)) { throw "wpr.exe was not found." }

    $statusOutput = @(& $wpr -status 2>&1)
    if (($statusOutput -join "`n") -notmatch 'WPR is not recording') {
        throw "WPR is already recording. Refusing to disturb an existing recording. Stop it yourself or use -Profiler None."
    }

    $startOutput = @(& $wpr -start CPU -filemode 2>&1)
    if ($LASTEXITCODE -ne 0) {
        throw "Could not start WPR CPU sampling for '$Label'. Run this PowerShell elevated if required, or use -Profiler None.`n$($startOutput -join [Environment]::NewLine)"
    }
    Write-Host "WPR_CPU_START|label=$Label|profile=CPU|mode=file"
}

function Stop-WprCpuCapture {
    param([string]$Label)

    $wpr = Get-WprPath
    $tracePath = Join-Path $outputBase ("physical_input_cpu_{0}.etl" -f $Label)
    $stopOutput = @(& $wpr -stop $tracePath 2>&1)
    if ($LASTEXITCODE -ne 0) {
        Write-Warning "WPR stop failed for '$Label': $($stopOutput -join [Environment]::NewLine)"
        return ""
    }
    Write-Host "WPR_CPU_SAVED|label=$Label|trace=$tracePath"
    return $tracePath
}

function Collect-ProfileOutput {
    param(
        [string]$Label,
        [string]$ProjectPath
    )

    $sourceDir = Join-Path $ProjectPath "test\_temp"
    foreach ($name in @("physical_input_profile.csv", "physical_input_summary.txt")) {
        $source = Join-Path $sourceDir $name
        if (-not (Test-Path -LiteralPath $source -PathType Leaf)) { continue }
        $stem = [IO.Path]::GetFileNameWithoutExtension($name)
        $ext = [IO.Path]::GetExtension($name)
        $destination = Join-Path $outputBase ("{0}_{1}{2}" -f $stem, $Label, $ext)
        Copy-Item -LiteralPath $source -Destination $destination -Force
        Write-Host "Captured: $destination"
    }
}

function Write-CaptureManifest {
    param(
        [string]$Label,
        [string]$ProjectPath,
        [int]$ProcessId,
        [string]$ProfilerName,
        [datetime]$Started,
        [datetime]$Ended,
        [string]$TracePath
    )

    $manifest = Join-Path $outputBase ("physical_input_capture_{0}.txt" -f $Label)
    @(
        "label=$Label",
        "plugin_version=$(Get-PluginVersion $ProjectPath)",
        "pid=$ProcessId",
        "profiler=$ProfilerName",
        "started_utc=$($Started.ToUniversalTime().ToString('o'))",
        "ended_utc=$($Ended.ToUniversalTime().ToString('o'))",
        "project=$ProjectPath",
        "trace=$TracePath"
    ) | Set-Content -LiteralPath $manifest -Encoding UTF8
    Write-Host "Capture manifest: $manifest"
}

function Invoke-ProfileHostSmokeTest {
    param(
        [string]$Label,
        [string]$ProjectPath
    )

    $editorLog = Join-Path $ProjectPath "test\_temp\smoke_editor.log"
    $process = Start-Process `
        -FilePath $godot.Gui `
        -ArgumentList @(
            "--editor",
            "--path", $ProjectPath,
            "--quit-after", "120",
            "--log-file", $editorLog
        ) `
        -PassThru

    if (-not $process.WaitForExit(30000)) {
        Stop-Process -Id $process.Id -Force -ErrorAction SilentlyContinue
        throw "Physical-input host smoke test timed out for '$Label'."
    }

    $text = if (Test-Path -LiteralPath $editorLog -PathType Leaf) {
        Get-Content -Raw -LiteralPath $editorLog
    } else {
        ""
    }
    if (Test-LogHasScriptFailure $text) {
        throw "Physical-input host smoke test reported a script failure for '$Label'. See $editorLog"
    }
    if ($text -notmatch 'PHYSICAL_INPUT_PROBE_START') {
        throw "Physical-input probe did not initialize for '$Label'. See $editorLog"
    }

    Write-Host "PROFILE_HOST_SMOKE_PASS|label=$Label|version=$(Get-PluginVersion $ProjectPath)"
}

function Invoke-SingleCapture {
    param(
        [string]$Label,
        [string]$ProjectPath,
        [string]$ProfilerName
    )

    $editorLog = Join-Path $ProjectPath "test\_temp\editor.log"
    $started = Get-Date
    $wprStarted = $false
    $tracePath = ""
    $process = $null

    try {
        if ($ProfilerName -eq "WPR") {
            Start-WprCpuCapture -Label $Label
            $wprStarted = $true
        }

        $process = Start-Process `
            -FilePath $godot.Gui `
            -ArgumentList @(
                "--editor",
                "--path", $ProjectPath,
                "--position", "80,80",
                "--log-file", $editorLog
            ) `
            -PassThru
        Write-Host ("PROFILE_EDITOR|label={0}|version={1}|pid={2}|project={3}" -f $Label, (Get-PluginVersion $ProjectPath), $process.Id, $ProjectPath)
        $process.WaitForExit()
    } finally {
        if ($wprStarted) {
            $tracePath = Stop-WprCpuCapture -Label $Label
        }
    }

    $ended = Get-Date
    Collect-ProfileOutput -Label $Label -ProjectPath $ProjectPath
    Write-CaptureManifest `
        -Label $Label `
        -ProjectPath $ProjectPath `
        -ProcessId $(if ($null -ne $process) { $process.Id } else { -1 }) `
        -ProfilerName $ProfilerName `
        -Started $started `
        -Ended $ended `
        -TracePath $tracePath
}

function Read-KeyValueSummary {
    param([string]$Path)
    $result = @{}
    if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) { return $result }
    foreach ($line in Get-Content -LiteralPath $Path) {
        $parts = $line -split '=', 2
        if ($parts.Count -eq 2) { $result[$parts[0]] = $parts[1] }
    }
    return $result
}

function Write-AbComparisonIfAvailable {
    $currentPath = Join-Path $outputBase "physical_input_summary_current.txt"
    $v109Path = Join-Path $outputBase "physical_input_summary_v1.0.9.txt"
    if (-not (Test-Path -LiteralPath $currentPath -PathType Leaf) -or -not (Test-Path -LiteralPath $v109Path -PathType Leaf)) {
        return
    }

    $current = Read-KeyValueSummary $currentPath
    $v109 = Read-KeyValueSummary $v109Path
    $keys = @(
        "drag_motion_events",
        "frames_with_drag_motion",
        "max_events_per_frame",
        "events_per_frame_p50",
        "events_per_frame_p95",
        "events_per_frame_p99",
        "events_per_frame_max",
        "oldest_event_to_draw_us_p50",
        "oldest_event_to_draw_us_p95",
        "oldest_event_to_draw_us_p99",
        "oldest_event_to_draw_us_max",
        "newest_event_to_draw_us_p50",
        "newest_event_to_draw_us_p95",
        "newest_event_to_draw_us_p99",
        "newest_event_to_draw_us_max"
    )

    $comparisonPath = Join-Path $outputBase "physical_input_ab_comparison.txt"
    $lines = @(
        "Physical input A/B comparison",
        "current=1.1.0 working tree host",
        "baseline=v1.0.9 local tag host",
        "delta=current-v1.0.9",
        ""
    )
    foreach ($key in $keys) {
        if (-not $current.ContainsKey($key) -or -not $v109.ContainsKey($key)) { continue }
        $currentValue = 0.0
        $v109Value = 0.0
        if (-not [double]::TryParse($current[$key], [ref]$currentValue)) { continue }
        if (-not [double]::TryParse($v109[$key], [ref]$v109Value)) { continue }
        $delta = $currentValue - $v109Value
        $percent = if ([math]::Abs($v109Value) -gt 0.000001) { 100.0 * $delta / $v109Value } else { 0.0 }
        $lines += ("{0}: current={1:F1} v1.0.9={2:F1} delta={3:+0.0;-0.0;0.0} ({4:+0.0;-0.0;0.0}%)" -f $key, $currentValue, $v109Value, $delta, $percent)
    }
    $lines | Set-Content -LiteralPath $comparisonPath -Encoding UTF8
    Write-Host "A/B summary: $comparisonPath"
}

function Remove-PreparedProjects {
    param([System.Collections.IDictionary]$PreparedProjects)
    foreach ($projectPath in $PreparedProjects.Values) {
        Remove-Item -LiteralPath $projectPath -Recurse -Force -ErrorAction SilentlyContinue
    }
    if ((Test-Path -LiteralPath $tempBase -PathType Container) -and -not (Get-ChildItem -LiteralPath $tempBase -Force | Select-Object -First 1)) {
        Remove-Item -LiteralPath $tempBase -Force -ErrorAction SilentlyContinue
    }
}

$projectRoot = Resolve-ProjectRoot
$godot = Resolve-GodotExecutables -RequestedPath $GodotPath
$tempBase = Join-Path $projectRoot "test\_temp\physical-input-projects"
$outputBase = Join-Path $projectRoot "test\_temp"
New-Item -ItemType Directory -Force -Path $tempBase | Out-Null

$resolvedProfiler = "None"
if (-not $PrepareOnly -and -not $SmokeTest) {
    $resolvedProfiler = Resolve-ProfilerMode -RequestedProfiler $Profiler
}

$projects = [ordered]@{}
if ($Mode -in @("Current", "Both", "SequentialAB")) {
    $projects["current"] = Prepare-ProfileProject -Label "current" -SourceKind "current"
}
if ($Mode -in @("V109", "Both", "SequentialAB")) {
    $projects["v1.0.9"] = Prepare-ProfileProject -Label "v1.0.9" -SourceKind "v109"
}

Write-Host ""
Write-Host "Prepared physical-input profile hosts:" -ForegroundColor Cyan
foreach ($entry in $projects.GetEnumerator()) {
    Write-Host ("  {0}: version={1} path={2}" -f $entry.Key, (Get-PluginVersion $entry.Value), $entry.Value)
}

if ($PrepareOnly) {
    Write-Host "PrepareOnly complete; no editor was launched."
    exit 0
}

if ($SmokeTest) {
    if ($Mode -eq "Both") {
        $smokeProcesses = [ordered]@{}
        $index = 0
        foreach ($entry in $projects.GetEnumerator()) {
            $position = if ($index -eq 0) { "40,80" } else { "1000,80" }
            $editorLog = Join-Path $entry.Value "test\_temp\smoke_editor.log"
            $process = Start-Process `
                -FilePath $godot.Gui `
                -ArgumentList @(
                    "--editor", "--path", $entry.Value,
                    "--position", $position,
                    "--quit-after", "120",
                    "--log-file", $editorLog
                ) `
                -PassThru
            $smokeProcesses[$entry.Key] = $process
            $index += 1
        }
        foreach ($entry in $smokeProcesses.GetEnumerator()) {
            if (-not $entry.Value.WaitForExit(30000)) {
                Stop-Process -Id $entry.Value.Id -Force -ErrorAction SilentlyContinue
                throw "Side-by-side physical-input smoke test timed out for '$($entry.Key)'."
            }
            $editorLog = Join-Path $projects[$entry.Key] "test\_temp\smoke_editor.log"
            $text = if (Test-Path -LiteralPath $editorLog -PathType Leaf) { Get-Content -Raw -LiteralPath $editorLog } else { "" }
            if (Test-LogHasScriptFailure $text) {
                throw "Side-by-side physical-input smoke test reported a script failure for '$($entry.Key)'. See $editorLog"
            }
            if ($text -notmatch 'PHYSICAL_INPUT_PROBE_START') {
                throw "Side-by-side physical-input probe did not initialize for '$($entry.Key)'. See $editorLog"
            }
            Write-Host "PROFILE_SIDE_BY_SIDE_SMOKE_PASS|label=$($entry.Key)|version=$(Get-PluginVersion $projects[$entry.Key])|pid=$($entry.Value.Id)"
        }
    } else {
        foreach ($entry in $projects.GetEnumerator()) {
            Invoke-ProfileHostSmokeTest -Label $entry.Key -ProjectPath $entry.Value
        }
    }
    if (-not $KeepProjects) { Remove-PreparedProjects $projects }
    Write-Host "Physical-input profile host smoke tests passed."
    exit 0
}

Write-Host ""
Write-Host "Capture protocol:" -ForegroundColor Cyan
Write-Host "  1. Warm up P2 with two full left/right crossing cycles."
Write-Host "  2. Click 'Start / Reset Capture' in the Easing Curve Input Probe panel."
Write-Host "  3. Perform exactly 10 full left -> right -> left crossing cycles at a comfortable, repeatable pace."
Write-Host "  4. Click 'Save & Close'. Do not change mouse polling-rate/DPI settings between versions."
Write-Host ""
if ($Mode -eq "Both") {
    Write-Host "Both mode is for subjective side-by-side feel only. Do not use its timing numbers as the controlled performance A/B." -ForegroundColor Yellow
    Write-Host "For controlled sampling, use -Mode SequentialAB so the editors run one at a time." -ForegroundColor Yellow
} elseif ($Mode -eq "SequentialAB") {
    Write-Host "SequentialAB will capture current first, then v1.0.9, so the two editors never compete for CPU/GPU resources."
    if ($resolvedProfiler -eq "WPR") {
        Write-Host "A separate WPR CPU-sampling ETL will be recorded for each version."
    }
} elseif ($resolvedProfiler -eq "WPR") {
    Write-Host "WPR CPU sampling will start immediately before the editor and stop when Save & Close exits it."
    Write-Host "The ETL is system-wide; filter CPU Usage (Sampled) by the PROFILE_EDITOR PID printed below."
}
Write-Host ""

if ($Mode -eq "Both") {
    $processes = [ordered]@{}
    $index = 0
    foreach ($entry in $projects.GetEnumerator()) {
        $position = if ($index -eq 0) { "40,80" } else { "1000,80" }
        $editorLog = Join-Path $entry.Value "test\_temp\editor.log"
        $process = Start-Process `
            -FilePath $godot.Gui `
            -ArgumentList @("--editor", "--path", $entry.Value, "--position", $position, "--log-file", $editorLog) `
            -PassThru
        $processes[$entry.Key] = $process
        Write-Host ("PROFILE_EDITOR|label={0}|version={1}|pid={2}|project={3}" -f $entry.Key, (Get-PluginVersion $entry.Value), $process.Id, $entry.Value)
        $index += 1
    }

    foreach ($entry in $processes.GetEnumerator()) {
        $entry.Value.WaitForExit()
        Collect-ProfileOutput -Label $entry.Key -ProjectPath $projects[$entry.Key]
        Write-CaptureManifest `
            -Label $entry.Key `
            -ProjectPath $projects[$entry.Key] `
            -ProcessId $entry.Value.Id `
            -ProfilerName "None-side-by-side" `
            -Started (Get-Date) `
            -Ended (Get-Date) `
            -TracePath ""
    }
} else {
    foreach ($entry in $projects.GetEnumerator()) {
        Invoke-SingleCapture -Label $entry.Key -ProjectPath $entry.Value -ProfilerName $resolvedProfiler
    }
}

if ($Mode -eq "Both") {
    Write-Host "Side-by-side capture complete; controlled A/B comparison is intentionally not generated from concurrent-editor timings." -ForegroundColor Yellow
} else {
    Write-AbComparisonIfAvailable
}

if (-not $KeepProjects) {
    Remove-PreparedProjects $projects
}

Write-Host "Physical-input profile capture complete."
