[CmdletBinding()]
param(
	[Parameter()]
	[string]$GodotPath = "",
	[Parameter(Position = 0, ValueFromRemainingArguments = $true)]
	[string[]]$CommandArguments
)

$ErrorActionPreference = "Stop"

function Resolve-ProjectRoot {
	$candidate = (Resolve-Path $PSScriptRoot).Path
	while ($true) {
		if (Test-Path -LiteralPath (Join-Path $candidate "project.godot") -PathType Leaf) {
			return $candidate
		}
		$parent = Split-Path -Parent $candidate
		if ([string]::IsNullOrWhiteSpace($parent) -or $parent -eq $candidate) {
			throw "Could not locate project.godot above runner directory: $PSScriptRoot"
		}
		$candidate = $parent
	}
}

$projectRoot = Resolve-ProjectRoot
$godotLauncher = Join-Path $PSScriptRoot "run_godot.ps1"
$suiteTimeoutSeconds = 60
$killWaitMilliseconds = 5000
$powerShellExecutable = (Get-Process -Id $PID).Path
$testTempDirectory = Join-Path $projectRoot "test\_temp"
$runnerTempDirectory = Join-Path $testTempDirectory "runner"
$isolatedProjectDirectory = Join-Path $runnerTempDirectory (
	"isolated-project-{0}" -f [guid]::NewGuid().ToString("N")
)

function Copy-IsolatedProjectDirectory {
	param(
		[string]$RelativePath,
		[string]$DestinationRoot
	)

	$source = Join-Path $projectRoot $RelativePath
	if (-not (Test-Path -LiteralPath $source -PathType Container)) {
		throw "Required isolated-test source directory was not found: $source"
	}

	$destination = Join-Path $DestinationRoot $RelativePath
	$destinationParent = Split-Path -Parent $destination
	New-Item -ItemType Directory -Force -Path $destinationParent | Out-Null
	Copy-Item -LiteralPath $source -Destination $destination -Recurse -Force
}

function New-IsolatedTestProject {
	param([string]$DestinationRoot)

	New-Item -ItemType Directory -Force -Path $DestinationRoot | Out-Null

	foreach ($relativePath in @(
		"addons\easing_curve",
		"test\scripts",
		"test\presets"
	)) {
		Copy-IsolatedProjectDirectory `
			-RelativePath $relativePath `
			-DestinationRoot $DestinationRoot
	}

	$projectConfig = @'
; Generated by test/runners/run_all_tests.ps1.
; This host intentionally excludes unrelated development plugins and autoloads.
config_version=5

[application]

config/name="Easing Curve Isolated Tests"
config/features=PackedStringArray("4.7", "GL Compatibility")

[editor_plugins]

enabled=PackedStringArray("res://addons/easing_curve/plugin.cfg")

[rendering]

renderer/rendering_method="gl_compatibility"
renderer/rendering_method.mobile="gl_compatibility"
'@
	[IO.File]::WriteAllText(
		(Join-Path $DestinationRoot "project.godot"),
		$projectConfig,
		[Text.UTF8Encoding]::new($false)
	)

	$isolatedTempDirectory = Join-Path $DestinationRoot "test\_temp"
	New-Item -ItemType Directory -Force -Path $isolatedTempDirectory | Out-Null
	[IO.File]::WriteAllText(
		(Join-Path $isolatedTempDirectory ".gdignore"),
		"",
		[Text.UTF8Encoding]::new($false)
	)
}

function Remove-DirectoryIfEmpty {
	param([string]$Path)

	if ([string]::IsNullOrWhiteSpace($Path) -or -not (Test-Path -LiteralPath $Path -PathType Container)) {
		return
	}

	if (-not (Get-ChildItem -LiteralPath $Path -Force | Select-Object -First 1)) {
		Remove-Item -LiteralPath $Path -Force -ErrorAction SilentlyContinue
	}
}

function Clear-TestTempArtifacts {
	# Keep test/_temp and its tracked .gdignore so Godot does not scan transient
	# test output. Everything else in this directory is runner-owned output.
	New-Item -ItemType Directory -Force -Path $testTempDirectory | Out-Null
	Get-ChildItem -LiteralPath $testTempDirectory -Force |
		Where-Object { $_.Name -ne ".gdignore" } |
		ForEach-Object {
			Remove-Item -LiteralPath $_.FullName -Recurse -Force
		}
}

$suites = @(
	@{ Name = "css_linear_test.gd"; Editor = $false },
	@{ Name = "easing_curve_editor_rmb_delete_test.gd"; Editor = $false },
	@{ Name = "easing_curve_manual_reorder_test.gd"; Editor = $false },
	@{ Name = "easing_curve_transform_test.gd"; Editor = $false },
	@{ Name = "easing_curve_v105_regression_test.gd"; Editor = $false },
	@{ Name = "runtime_curve_updates_test.gd"; Editor = $false },
	@{ Name = "serialization_transition_contract_test.gd"; Editor = $false },
	@{ Name = "tween_equivalence_test.gd"; Editor = $false },
	@{ Name = "easing_curve_control_editability_test.gd"; Editor = $true },
	@{ Name = "easing_curve_preview_generator_test.gd"; Editor = $true },
	@{ Name = "easing_curve_editor_position_x_drag_test.gd"; Editor = $true },
	@{ Name = "easing_curve_linear_control_alias_test.gd"; Editor = $true },
	@{ Name = "easing_curve_points_list_add_editor_test.gd"; Editor = $true },
	@{ Name = "easing_curve_points_list_reorder_editor_test.gd"; Editor = $true },
	@{ Name = "easing_curve_point_state_characterization_test.gd"; Editor = $true },
	@{ Name = "easing_curve_selection_refresh_characterization_test.gd"; Editor = $true },
	@{ Name = "easing_curve_editor_gesture_characterization_test.gd"; Editor = $true },
	@{ Name = "editor_undo_redo_test.gd"; Editor = $true }
)

function Show-Help {
	Write-Host "Usage: .\\run_all_tests.ps1 [--help | --list | --run | --cleanup] [-GodotPath <path>]"
	Write-Host ""
	Write-Host "Options:"
	Write-Host "  --help  Show this help menu."
	Write-Host "  --list  List the individual unit tests run by this script."
	Write-Host "  --run   Run all listed unit tests."
	Write-Host "  --cleanup  Remove successful-run artifacts from test/_temp, preserving .gdignore."
	Write-Host ""
	Write-Host "-GodotPath may be supplied with --run to select a Godot executable."
}

if ($CommandArguments.Count -ne 1) {
	Show-Help
	if ($CommandArguments.Count -gt 1) {
		Write-Error "Specify exactly one command: --help, --list, --run, or --cleanup."
	}
	exit $(if ($CommandArguments.Count -eq 0) { 0 } else { 1 })
}

switch ($CommandArguments[0]) {
	"--help" {
		Show-Help
		exit 0
	}
	"--list" {
		foreach ($suite in $suites) {
			Write-Output $suite.Name
		}
		exit 0
	}
	"--cleanup" {
		Clear-TestTempArtifacts
		Write-Host "Cleaned test/_temp artifacts; preserved .gdignore."
		exit 0
	}
	"--run" { }
	default {
		Show-Help
		Write-Error "Unknown command: $($CommandArguments[0])"
		exit 1
	}
}

New-Item -ItemType Directory -Force -Path $runnerTempDirectory | Out-Null
New-IsolatedTestProject -DestinationRoot $isolatedProjectDirectory
Write-Host "Isolated test project: $isolatedProjectDirectory"

$commonGodotDiagnosticPatterns = @(
	# Godot 4.7.1 can emit this before project scripts run when the Windows
	# certificate store is unavailable. The isolated product-only host confirms
	# that it is not produced by a development plugin or test behavior.
	'^ERROR: Failed to read the root certificate store[.]$'
)

$commonEditorDiagnosticPatterns = @(
	'^WARNING: Scan thread aborted[.][.][.]$',
	'^WARNING: [0-9]+ RIDs of type "Canvas" were leaked[.]$',
	'^WARNING: [0-9]+ RIDs of type "CanvasItem" were leaked[.]$',
	'^WARNING: [0-9]+ ObjectDB instances were leaked at exit [(]run with `--verbose` for details[)][.]$',
	"^ERROR: [0-9]+ RID allocations of type '.+' were leaked at exit[.]$"
)

$suiteDiagnosticPatterns = @{
	"serialization_transition_contract_test.gd" = @(
		"^ERROR: Point property 'malformed_missing_lifecycle' is missing required 'snapshot_lifecycle'[.] Allowed values: 'ordinary', 'semantic'[.]$",
		"^ERROR: Point property 'malformed_invalid_lifecycle' has invalid snapshot lifecycle 'invalid'[.] Allowed values: 'ordinary', 'semantic'[.]$",
		"^ERROR: Unknown point property 'unknown'[.]$"
	)
	"easing_curve_editor_gesture_characterization_test.gd" = @(
		'^ERROR: [0-9]+ resources still in use at exit [(]run with --verbose for details[)][.]$'
	)
}

function Get-TopLevelDiagnostics {
	param([string[]]$TextSources)

	$diagnostics = @()
	foreach ($text in $TextSources) {
		if ([string]::IsNullOrWhiteSpace($text)) {
			continue
		}
		foreach ($line in ($text -split '\r?\n')) {
			$trimmed = $line.Trim()
			if ($trimmed -match '^(?:SCRIPT ERROR:|ERROR:|WARNING:)') {
				$diagnostics += $trimmed
			}
		}
	}
	return @($diagnostics | Sort-Object -Unique)
}

function Test-DiagnosticAllowed {
	param(
		[string]$Diagnostic,
		[string]$SuiteName,
		[bool]$IsEditor
	)

	if ($Diagnostic -match '^SCRIPT ERROR:') {
		return $false
	}

	foreach ($pattern in $commonGodotDiagnosticPatterns) {
		if ($Diagnostic -match $pattern) {
			return $true
		}
	}

	if ($IsEditor) {
		foreach ($pattern in $commonEditorDiagnosticPatterns) {
			if ($Diagnostic -match $pattern) {
				return $true
			}
		}
	}

	if ($suiteDiagnosticPatterns.ContainsKey($SuiteName)) {
		foreach ($pattern in $suiteDiagnosticPatterns[$SuiteName]) {
			if ($Diagnostic -match $pattern) {
				return $true
			}
		}
	}

	return $false
}

function Initialize-IsolatedTestProject {
	$bootstrapDirectory = Join-Path $runnerTempDirectory (
		"bootstrap-{0}" -f [guid]::NewGuid().ToString("N")
	)
	New-Item -ItemType Directory -Force -Path $bootstrapDirectory | Out-Null

	$stdoutPath = Join-Path $bootstrapDirectory "stdout.txt"
	$stderrPath = Join-Path $bootstrapDirectory "stderr.txt"
	$exitCodePath = Join-Path $bootstrapDirectory "exitcode.txt"
	$godotLogPath = Join-Path $bootstrapDirectory "godot.log"
	$appDataPath = Join-Path $bootstrapDirectory "appdata"
	$initialized = $false

	try {
		$launcherArguments = @(
			"-NoProfile",
			"-ExecutionPolicy", "Bypass",
			"-File", $godotLauncher,
			"-ExitCodeFile", $exitCodePath,
			"-AppDataDirectory", $appDataPath
		)
		if (-not [string]::IsNullOrWhiteSpace($GodotPath)) {
			$launcherArguments += @("-GodotPath", $GodotPath)
		}
		$launcherArguments += @(
			"--editor",
			"--headless",
			"--path", $isolatedProjectDirectory,
			"--import",
			"--log-file", $godotLogPath
		)

		$bootstrapProcess = Start-Process `
			-FilePath $powerShellExecutable `
			-ArgumentList $launcherArguments `
			-WorkingDirectory $isolatedProjectDirectory `
			-RedirectStandardOutput $stdoutPath `
			-RedirectStandardError $stderrPath `
			-WindowStyle Hidden `
			-PassThru

		if (-not $bootstrapProcess.WaitForExit($suiteTimeoutSeconds * 1000)) {
			& taskkill.exe /PID $bootstrapProcess.Id /T /F 2>$null | Out-Null
			throw "Isolated test project bootstrap timed out after $suiteTimeoutSeconds seconds."
		}
		$bootstrapProcess.WaitForExit()

		$stdout = if (Test-Path -LiteralPath $stdoutPath) { Get-Content -Raw -LiteralPath $stdoutPath } else { "" }
		$stderr = if (Test-Path -LiteralPath $stderrPath) { Get-Content -Raw -LiteralPath $stderrPath } else { "" }
		$godotLog = if (Test-Path -LiteralPath $godotLogPath) { Get-Content -Raw -LiteralPath $godotLogPath } else { "" }
		if ($stdout) { Write-Host $stdout.TrimEnd() }
		if ($stderr) { Write-Host $stderr.TrimEnd() }

		if (-not (Test-Path -LiteralPath $exitCodePath -PathType Leaf)) {
			throw "Isolated test project bootstrap did not report an exit code."
		}
		$exitCodeText = (Get-Content -Raw -LiteralPath $exitCodePath).Trim()
		if ($exitCodeText -notmatch '^-?\d+$' -or [int]$exitCodeText -ne 0) {
			throw "Isolated test project bootstrap exited with code '$exitCodeText'."
		}

		$diagnostics = @(Get-TopLevelDiagnostics -TextSources @($stdout, $stderr, $godotLog))
		$unexpectedDiagnostics = @()
		foreach ($diagnostic in $diagnostics) {
			if (-not (Test-DiagnosticAllowed -Diagnostic $diagnostic -SuiteName "" -IsEditor $true)) {
				$unexpectedDiagnostics += $diagnostic
			}
		}
		if ($unexpectedDiagnostics.Count -gt 0) {
			Write-Host "Unexpected isolated-project bootstrap diagnostics:" -ForegroundColor Red
			foreach ($diagnostic in $unexpectedDiagnostics) {
				Write-Host "  $diagnostic" -ForegroundColor Red
			}
			throw "Isolated test project bootstrap reported unexpected diagnostics."
		}

		$classCachePath = Join-Path $isolatedProjectDirectory ".godot\global_script_class_cache.cfg"
		if (-not (Test-Path -LiteralPath $classCachePath -PathType Leaf)) {
			throw "Isolated test project bootstrap did not create the global script class cache."
		}

		$initialized = $true
		Write-Host "Initialized isolated Godot class cache."
	}
	finally {
		if ($initialized) {
			Remove-Item -LiteralPath $bootstrapDirectory -Recurse -Force -ErrorAction SilentlyContinue
		} else {
			Write-Host "Preserved bootstrap artifacts: $bootstrapDirectory" -ForegroundColor Yellow
		}
	}
}

Initialize-IsolatedTestProject

$results = @()
foreach ($suite in $suites) {
	$mode = if ($suite.Editor) { "editor-host" } else { "headless" }
	Write-Host "`n=== $($suite.Name) [$mode] ==="

	$suiteBaseName = [IO.Path]::GetFileNameWithoutExtension($suite.Name)
	$suiteTempDirectory = Join-Path $runnerTempDirectory (
		"{0}-{1}" -f $suiteBaseName, [guid]::NewGuid().ToString("N")
	)
	New-Item -ItemType Directory -Force -Path $suiteTempDirectory | Out-Null
	$stdoutPath = Join-Path $suiteTempDirectory "stdout.txt"
	$stderrPath = Join-Path $suiteTempDirectory "stderr.txt"
	$exitCodePath = Join-Path $suiteTempDirectory "exitcode.txt"
	$godotLogPath = Join-Path $suiteTempDirectory "godot.log"
	$suiteAppDataPath = Join-Path $suiteTempDirectory "appdata"

	$arguments = @()
	if ($suite.Editor) {
		$arguments += "--editor"
	}
	$arguments += @(
		"--headless",
		"--path", $isolatedProjectDirectory,
		"--script", "res://test/scripts/unit/$($suite.Name)",
		"--log-file", $godotLogPath
	)

	$suiteExitCode = -1
	$timedOut = $false
	$passed = $false
	try {
		$suiteTimeout = if ($suite.ContainsKey("TimeoutSeconds")) { $suite.TimeoutSeconds } else { $suiteTimeoutSeconds }
		$launcherArguments = @(
			"-NoProfile",
			"-ExecutionPolicy", "Bypass",
			"-File", $godotLauncher,
			"-ExitCodeFile", $exitCodePath,
			"-AppDataDirectory", $suiteAppDataPath
		)
		if (-not [string]::IsNullOrWhiteSpace($GodotPath)) {
			$launcherArguments += @("-GodotPath", $GodotPath)
		}
		$launcherArguments += $arguments
		$startProcessArguments = @{
			FilePath = $powerShellExecutable
			ArgumentList = $launcherArguments
			WorkingDirectory = $isolatedProjectDirectory
			RedirectStandardOutput = $stdoutPath
			RedirectStandardError = $stderrPath
			WindowStyle = "Hidden"
			PassThru = $true
		}
		$launcherProcess = Start-Process @startProcessArguments
		$completed = $launcherProcess.WaitForExit([int]($suiteTimeout * 1000))
		if ($completed) {
			# Process is already exited; this final wait synchronizes redirected streams.
			$launcherProcess.WaitForExit()
			if (Test-Path -LiteralPath $exitCodePath) {
				$exitCodeText = (Get-Content -Raw -LiteralPath $exitCodePath).Trim()
				if ($exitCodeText -match '^-?\d+$') {
					$suiteExitCode = [int]$exitCodeText
				} else {
					Write-Warning "Invalid exit code from $($suite.Name): '$exitCodeText'"
				}
			} else {
				Write-Warning "No exit code was reported for $($suite.Name)."
			}
		} else {
			$timedOut = $true
			Write-Host "Timed out after $suiteTimeout seconds; terminating process tree rooted at PID $($launcherProcess.Id)." -ForegroundColor Yellow
			& taskkill.exe /PID $launcherProcess.Id /T /F 2>$null | Out-Null
			if (-not $launcherProcess.WaitForExit($killWaitMilliseconds)) {
				Write-Warning (
					"Process tree rooted at PID $($launcherProcess.Id) " +
					"did not exit after taskkill."
				)
			}
		}
		$stdout = if (Test-Path -LiteralPath $stdoutPath) { Get-Content -Raw -LiteralPath $stdoutPath } else { "" }
		$stderr = if (Test-Path -LiteralPath $stderrPath) { Get-Content -Raw -LiteralPath $stderrPath } else { "" }
		$godotLog = if (Test-Path -LiteralPath $godotLogPath) { Get-Content -Raw -LiteralPath $godotLogPath } else { "" }
		$output = "$stdout`n$stderr"
		if ($stdout) { Write-Host $stdout.TrimEnd() }
		if ($stderr) { Write-Host $stderr.TrimEnd() }
		$hasPass = $output -match '(?m)^PASS:'
		$diagnostics = @(Get-TopLevelDiagnostics -TextSources @($stdout, $stderr, $godotLog))
		$allowedDiagnostics = @()
		$unexpectedDiagnostics = @()
		foreach ($diagnostic in $diagnostics) {
			if (Test-DiagnosticAllowed -Diagnostic $diagnostic -SuiteName $suite.Name -IsEditor $suite.Editor) {
				$allowedDiagnostics += $diagnostic
			} else {
				$unexpectedDiagnostics += $diagnostic
			}
		}
		$hasScriptError = @($diagnostics | Where-Object { $_ -match '^SCRIPT ERROR:' }).Count -gt 0
		if ($allowedDiagnostics.Count -gt 0) {
			Write-Host "Allowed diagnostics: $($allowedDiagnostics.Count)"
		}
		if ($unexpectedDiagnostics.Count -gt 0) {
			Write-Host "Unexpected diagnostics:" -ForegroundColor Red
			foreach ($diagnostic in $unexpectedDiagnostics) {
				Write-Host "  $diagnostic" -ForegroundColor Red
			}
		}
		$passed = -not $timedOut -and $suiteExitCode -eq 0 -and $hasPass -and -not $hasScriptError -and $unexpectedDiagnostics.Count -eq 0
		$results += [pscustomobject]@{
			Suite = $suite.Name
			Mode = $mode
			ExitCode = $suiteExitCode
			TimedOut = $timedOut
			PassMarker = $hasPass
			ScriptError = $hasScriptError
			AllowedDiagnostics = $allowedDiagnostics.Count
			UnexpectedDiagnostics = $unexpectedDiagnostics.Count
			Passed = $passed
		}
	} finally {
		if ($passed) {
			Remove-Item -LiteralPath $suiteTempDirectory -Recurse -Force -ErrorAction SilentlyContinue
		} else {
			Write-Host "Preserved temp artifacts: $suiteTempDirectory" -ForegroundColor Yellow
		}
	}
}

Write-Host "`n=== Test summary ==="
$results | Format-Table -AutoSize
$failed = @($results | Where-Object { -not $_.Passed })
if ($failed.Count -gt 0) {
	Write-Host "Preserved isolated test project: $isolatedProjectDirectory" -ForegroundColor Yellow
	Write-Host "$($failed.Count) of $($results.Count) suites failed." -ForegroundColor Red
	exit 1
}

Remove-Item `
	-LiteralPath $isolatedProjectDirectory `
	-Recurse `
	-Force `
	-ErrorAction SilentlyContinue
Remove-DirectoryIfEmpty $runnerTempDirectory

# Keep test/_temp itself: its tracked .gdignore prevents Godot from scanning
# transient test artifacts created beneath this directory.
Write-Host "All $($results.Count) suites passed."
exit 0
