[CmdletBinding()]
param([string]$GodotPath = "")

$ErrorActionPreference = "Stop"

$projectRoot = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
$validationRoot = Join-Path $projectRoot ("test\_temp\legacy-only-" + [guid]::NewGuid().ToString("N"))
$addonDestination = Join-Path $validationRoot "addons\easing_curve"
$logPath = Join-Path $validationRoot "test\_temp\legacy_without_native.log"
$bootstrapLogPath = Join-Path $validationRoot "test\_temp\bootstrap.log"
$runner = Join-Path $PSScriptRoot "run_godot.ps1"
$powerShellExecutable = (Get-Process -Id $PID).Path
$succeeded = $false

try {
	New-Item -ItemType Directory -Force -Path $addonDestination, (Split-Path -Parent $logPath) | Out-Null
	Copy-Item -LiteralPath (Join-Path $projectRoot "addons\easing_curve\assets") -Destination $addonDestination -Recurse -Force
	Copy-Item -LiteralPath (Join-Path $projectRoot "addons\easing_curve\scripts") -Destination $addonDestination -Recurse -Force
	Copy-Item -LiteralPath (Join-Path $projectRoot "addons\easing_curve\plugin.cfg") -Destination $addonDestination -Force
	Copy-Item -LiteralPath (Join-Path $projectRoot "addons\easing_curve\plugin.gd") -Destination $addonDestination -Force
	Copy-Item -LiteralPath (Join-Path $projectRoot "test\scripts\integration\legacy_without_native_main.gd") -Destination (Join-Path $validationRoot "main.gd") -Force

	$projectConfig = @'
; Generated by test/runners/run_legacy_without_native_test.ps1.
config_version=5

[application]

config/name="Easing Curve Legacy-Only Validation"
config/features=PackedStringArray("4.7", "GL Compatibility")

[editor_plugins]

enabled=PackedStringArray("res://addons/easing_curve/plugin.cfg")

[rendering]

renderer/rendering_method="gl_compatibility"
renderer/rendering_method.mobile="gl_compatibility"
'@
	[IO.File]::WriteAllText((Join-Path $validationRoot "project.godot"), $projectConfig, [Text.UTF8Encoding]::new($false))
	[IO.File]::WriteAllText((Join-Path $validationRoot "test\_temp\.gdignore"), "", [Text.UTF8Encoding]::new($false))

	$runnerArguments = @("-NoProfile", "-ExecutionPolicy", "Bypass", "-File", $runner)
	if (-not [string]::IsNullOrWhiteSpace($GodotPath)) {
		$runnerArguments += @("-GodotPath", $GodotPath)
	}
	$bootstrapArguments = $runnerArguments + @(
		"--editor", "--headless", "--path", $validationRoot, "--import", "--quit-after", "2",
		"--log-file", $bootstrapLogPath
	)
	& $powerShellExecutable @bootstrapArguments
	$bootstrapExitCode = $LASTEXITCODE
	$classCache = Join-Path $validationRoot ".godot\global_script_class_cache.cfg"
	$bootstrapText = if (Test-Path -LiteralPath $bootstrapLogPath) { Get-Content -Raw -LiteralPath $bootstrapLogPath } else { "" }
	if (
		$bootstrapExitCode -ne 0 -or
		-not (Test-Path -LiteralPath $classCache -PathType Leaf) -or
		$bootstrapText -match '(?m)^(?:SCRIPT ERROR:|.*Parse Error:|ERROR: Failed to load extension)'
	) {
		throw "Legacy-only editor bootstrap failed. Artifacts retained at $validationRoot"
	}

	$runnerArguments += @("--headless", "--path", $validationRoot, "--script", "res://main.gd", "--log-file", $logPath)
	& $powerShellExecutable @runnerArguments
	$exitCode = $LASTEXITCODE
	$logText = if (Test-Path -LiteralPath $logPath) { Get-Content -Raw -LiteralPath $logPath } else { "" }
	if ($exitCode -ne 0 -or $logText -notmatch '(?m)^PASS: legacy API loads, samples, and serializes without Native$') {
		throw "Legacy-only validation failed with exit code $exitCode. Artifacts retained at $validationRoot"
	}

	Write-Host "PASS: legacy-only project loaded with no GDExtension manifest or binary."
	$succeeded = $true
} finally {
	if ($succeeded -and (Test-Path -LiteralPath $validationRoot)) {
		Remove-Item -LiteralPath $validationRoot -Recurse -Force
	}
}
