[CmdletBinding()]
param(
    [ValidateSet("Current", "V109", "Both")]
    [string]$Mode = "Both",
    [string]$GodotPath = "",
    [switch]$PrepareOnly,
    [switch]$KeepProjects
)

$ErrorActionPreference = "Stop"

function Resolve-ProjectRoot {
    $candidate = (Resolve-Path $PSScriptRoot).Path
    while ($true) {
        if (Test-Path -LiteralPath (Join-Path $candidate "project.godot") -PathType Leaf) { return $candidate }
        $parent = Split-Path -Parent $candidate
        if ([string]::IsNullOrWhiteSpace($parent) -or $parent -eq $candidate) { throw "Could not locate project.godot above runner directory: $PSScriptRoot" }
        $candidate = $parent
    }
}

function Resolve-GodotExecutables {
    param([string]$RequestedPath)
    $fallback = "C:\Godot\4.7\engine\Godot_v4.7.1-stable_win64.exe\Godot_v4.7.1-stable_win64.exe"
    $gui = $RequestedPath
    if ([string]::IsNullOrWhiteSpace($gui)) { $gui = $env:EASING_CURVE_GODOT_PATH }
    if ([string]::IsNullOrWhiteSpace($gui)) { $gui = $fallback }
    if (-not (Test-Path -LiteralPath $gui -PathType Leaf)) { throw "Godot executable was not found: $gui" }
    $gui = (Resolve-Path -LiteralPath $gui).Path
    if ([IO.Path]::GetFileNameWithoutExtension($gui).EndsWith("_console", [StringComparison]::OrdinalIgnoreCase)) {
        $candidate = $gui -replace '_console\.exe$', '.exe'
        if (Test-Path -LiteralPath $candidate -PathType Leaf) { $gui = $candidate }
    }
    $console = Join-Path ([IO.Path]::GetDirectoryName($gui)) ([IO.Path]::GetFileNameWithoutExtension($gui) + "_console.exe")
    if (-not (Test-Path -LiteralPath $console -PathType Leaf)) { $console = $gui }
    return @{ Gui = $gui; Console = $console }
}

function Write-ProjectConfig {
    param([string]$Path, [string]$Label, [bool]$EnableProbe)
    $plugins = if ($EnableProbe) { 'PackedStringArray("res://addons/easing_curve/plugin.cfg", "res://addons/easing_curve_physical_input_probe/plugin.cfg")' } else { 'PackedStringArray("res://addons/easing_curve/plugin.cfg")' }
    $config = @"
; Generated by test/runners/run_physical_input_profile.ps1.
config_version=5
[application]
config/name="Easing Curve Physical Input — $Label"
config/features=PackedStringArray("4.7", "GL Compatibility")
[editor_plugins]
enabled=$plugins
[rendering]
renderer/rendering_method="gl_compatibility"
renderer/rendering_method.mobile="gl_compatibility"
"@
    [IO.File]::WriteAllText($Path, $config, [Text.UTF8Encoding]::new($false))
}

function Add-ProbeAddon {
    param([string]$ProjectPath)
    $probeAddon = Join-Path $ProjectPath "addons\easing_curve_physical_input_probe"
    New-Item -ItemType Directory -Force -Path $probeAddon | Out-Null
    Copy-Item -LiteralPath (Join-Path $projectRoot "test\scripts\performance\easing_curve_physical_input_probe.gd") -Destination (Join-Path $probeAddon "plugin.gd") -Force
    $pluginConfig = @'
[plugin]
name="Easing Curve Physical Input Probe"
description="Temporary physical mouse delivery and frame-latency capture."
author="Easing Curve tests"
version="1.0"
script="plugin.gd"
'@
    [IO.File]::WriteAllText((Join-Path $probeAddon "plugin.cfg"), $pluginConfig, [Text.UTF8Encoding]::new($false))
}

function Prepare-ProfileProject {
    param([string]$Label, [string]$SourceKind)
    $projectPath = Join-Path $tempBase $Label
    if (Test-Path -LiteralPath $projectPath) { Remove-Item -LiteralPath $projectPath -Recurse -Force }
    New-Item -ItemType Directory -Force -Path $projectPath | Out-Null

    if ($SourceKind -eq "current") {
        New-Item -ItemType Directory -Force -Path (Join-Path $projectPath "addons") | Out-Null
        Copy-Item -LiteralPath (Join-Path $projectRoot "addons\easing_curve") -Destination (Join-Path $projectPath "addons\easing_curve") -Recurse -Force
    } else {
        $archive = Join-Path $tempBase ("easing_curve_" + $Label + ".zip")
        & git -C $projectRoot archive --format=zip --output=$archive v1.0.9 addons/easing_curve
        if ($LASTEXITCODE -ne 0) { throw "Could not archive v1.0.9 from the local repository." }
        Expand-Archive -LiteralPath $archive -DestinationPath $projectPath -Force
        Remove-Item -LiteralPath $archive -Force
    }

    Add-ProbeAddon -ProjectPath $projectPath
    $temp = Join-Path $projectPath "test\_temp"
    New-Item -ItemType Directory -Force -Path $temp | Out-Null
    [IO.File]::WriteAllText((Join-Path $temp ".gdignore"), "", [Text.UTF8Encoding]::new($false))
    $projectConfig = Join-Path $projectPath "project.godot"
    Write-ProjectConfig -Path $projectConfig -Label $Label -EnableProbe $false

    $bootstrapLog = Join-Path $temp "bootstrap.log"
    & $godot.Console --editor --headless --path $projectPath --import --log-file $bootstrapLog
    $bootstrapExit = $LASTEXITCODE
    $cache = Join-Path $projectPath ".godot\global_script_class_cache.cfg"
    $bootstrapText = if (Test-Path -LiteralPath $bootstrapLog) { Get-Content -Raw -LiteralPath $bootstrapLog } else { "" }
    if (-not (Test-Path -LiteralPath $cache) -or $bootstrapText -match '(?m)^(?:SCRIPT ERROR:|.*Parse Error:|ERROR: Failed to load script)') {
        throw "Profile project '$Label' failed bootstrap validation (exit $bootstrapExit). See $bootstrapLog"
    }
    Write-ProjectConfig -Path $projectConfig -Label $Label -EnableProbe $true
    return $projectPath
}

function Collect-ProfileOutput {
    param([string]$Label, [string]$ProjectPath)
    $sourceDir = Join-Path $ProjectPath "test\_temp"
    foreach ($name in @("physical_input_profile.csv", "physical_input_summary.txt")) {
        $source = Join-Path $sourceDir $name
        if (Test-Path -LiteralPath $source -PathType Leaf) {
            $stem = [IO.Path]::GetFileNameWithoutExtension($name)
            $ext = [IO.Path]::GetExtension($name)
            $destination = Join-Path $outputBase ("{0}_{1}{2}" -f $stem, $Label, $ext)
            Copy-Item -LiteralPath $source -Destination $destination -Force
            Write-Host "Captured: $destination"
        }
    }
}

$projectRoot = Resolve-ProjectRoot
$godot = Resolve-GodotExecutables -RequestedPath $GodotPath
$tempBase = Join-Path $projectRoot "test\_temp\physical-input-projects"
$outputBase = Join-Path $projectRoot "test\_temp"
New-Item -ItemType Directory -Force -Path $tempBase | Out-Null

$projects = [ordered]@{}
if ($Mode -in @("Current", "Both")) { $projects["current"] = Prepare-ProfileProject -Label "current" -SourceKind "current" }
if ($Mode -in @("V109", "Both")) { $projects["v1.0.9"] = Prepare-ProfileProject -Label "v1.0.9" -SourceKind "v109" }

Write-Host ""
Write-Host "Prepared physical-input profile hosts:" -ForegroundColor Cyan
foreach ($entry in $projects.GetEnumerator()) { Write-Host ("  {0}: {1}" -f $entry.Key, $entry.Value) }
if ($PrepareOnly) {
    Write-Host "PrepareOnly complete; no editor was launched."
    exit 0
}

Write-Host ""
Write-Host "Instructions:" -ForegroundColor Cyan
Write-Host "  1. In each editor, drag P2 horizontally across several points and back repeatedly."
Write-Host "  2. Use the 'Easing Curve Input Probe' bottom panel and click 'Save & Close'."
Write-Host "  3. For external sampling, attach VerySleepy to the PID printed below while dragging."
Write-Host "  4. For cleaner CPU samples, prefer -Mode Current and -Mode V109 separately; -Mode Both is best for subjective side-by-side feel."
Write-Host ""

$processes = [ordered]@{}
$index = 0
foreach ($entry in $projects.GetEnumerator()) {
    $position = if ($index -eq 0) { "40,80" } else { "1000,80" }
    $editorLog = Join-Path $entry.Value "test\_temp\editor.log"
    $process = Start-Process -FilePath $godot.Gui -ArgumentList @("--editor", "--path", $entry.Value, "--position", $position, "--log-file", $editorLog) -PassThru
    $processes[$entry.Key] = $process
    Write-Host ("PROFILE_EDITOR|label={0}|pid={1}|project={2}" -f $entry.Key, $process.Id, $entry.Value)
    $index += 1
}

foreach ($entry in $processes.GetEnumerator()) {
    $entry.Value.WaitForExit()
    Collect-ProfileOutput -Label $entry.Key -ProjectPath $projects[$entry.Key]
}

if (-not $KeepProjects) {
    foreach ($projectPath in $projects.Values) { Remove-Item -LiteralPath $projectPath -Recurse -Force -ErrorAction SilentlyContinue }
    if ((Test-Path -LiteralPath $tempBase -PathType Container) -and -not (Get-ChildItem -LiteralPath $tempBase -Force | Select-Object -First 1)) { Remove-Item -LiteralPath $tempBase -Force -ErrorAction SilentlyContinue }
}
Write-Host "Physical-input profile capture complete."
