[CmdletBinding()]
param([string]$GodotPath = "")
$ErrorActionPreference = "Stop"

function Resolve-ProjectRoot {
    $candidate = (Resolve-Path $PSScriptRoot).Path
    while ($true) {
        if (Test-Path -LiteralPath (Join-Path $candidate "project.godot") -PathType Leaf) { return $candidate }
        $parent = Split-Path -Parent $candidate
        if ([string]::IsNullOrWhiteSpace($parent) -or $parent -eq $candidate) { throw "Could not locate project.godot above runner directory: $PSScriptRoot" }
        $candidate = $parent
    }
}

function Invoke-GodotRunner {
    param([string[]]$Arguments)
    $runnerArguments = @("-NoProfile", "-ExecutionPolicy", "Bypass", "-File", $godotRunner)
    if (-not [string]::IsNullOrWhiteSpace($GodotPath)) { $runnerArguments += @("-GodotPath", $GodotPath) }
    $runnerArguments += $Arguments
    & $powerShellExecutable @runnerArguments
    return $LASTEXITCODE
}

$projectRoot = Resolve-ProjectRoot
$godotRunner = Join-Path $PSScriptRoot "run_godot.ps1"
$powerShellExecutable = (Get-Process -Id $PID).Path
$tempBase = Join-Path $projectRoot "test\_temp\native-editor-script"
$tempProject = Join-Path $tempBase ([guid]::NewGuid().ToString("N"))
$isolatedTemp = Join-Path $tempProject "test\_temp"
$bootstrapLog = Join-Path $isolatedTemp "bootstrap.log"
$testLog = Join-Path $isolatedTemp "position_x_native.log"
$outputLog = Join-Path $projectRoot "test\_temp\position_x_native_editor_script.log"

New-Item -ItemType Directory -Force -Path $tempProject | Out-Null
foreach ($relativePath in @("addons\easing_curve", "test\scripts")) {
    $source = Join-Path $projectRoot $relativePath
    $destination = Join-Path $tempProject $relativePath
    New-Item -ItemType Directory -Force -Path (Split-Path -Parent $destination) | Out-Null
    Copy-Item -LiteralPath $source -Destination $destination -Recurse -Force
}
New-Item -ItemType Directory -Force -Path $isolatedTemp | Out-Null
[IO.File]::WriteAllText((Join-Path $isolatedTemp ".gdignore"), "", [Text.UTF8Encoding]::new($false))

$projectConfig = @'
; Generated by test/runners/run_native_editor_script_validation.ps1.
config_version=5
[application]
config/name="Easing Curve Native Editor Script Validation"
config/features=PackedStringArray("4.7", "GL Compatibility")
[editor_plugins]
enabled=PackedStringArray("res://addons/easing_curve/plugin.cfg")
[rendering]
renderer/rendering_method="gl_compatibility"
renderer/rendering_method.mobile="gl_compatibility"
'@
[IO.File]::WriteAllText((Join-Path $tempProject "project.godot"), $projectConfig, [Text.UTF8Encoding]::new($false))

Write-Host "Bootstrapping isolated native-editor test host..."
$bootstrapExit = Invoke-GodotRunner @("--editor", "--headless", "--path", $tempProject, "--import", "--log-file", $bootstrapLog)
$classCache = Join-Path $tempProject ".godot\global_script_class_cache.cfg"
$bootstrapText = if (Test-Path -LiteralPath $bootstrapLog) { Get-Content -Raw -LiteralPath $bootstrapLog } else { "" }
if (-not (Test-Path -LiteralPath $classCache) -or $bootstrapText -match '(?m)^(?:SCRIPT ERROR:|.*Parse Error:|ERROR: Failed to load script)') {
    Write-Host "Preserved failed validation project: $tempProject" -ForegroundColor Yellow
    exit 1
}
if ($bootstrapExit -ne 0) { Write-Warning "Bootstrap returned $bootstrapExit; cache and script diagnostics are clean, continuing." }

Write-Host "Replaying non-headless --editor --script position-X test..."
$testExit = Invoke-GodotRunner @(
    "--editor",
    "--path", $tempProject,
    "--script", "res://test/scripts/unit/easing_curve_editor_position_x_drag_test.gd",
    "--log-file", $testLog
)
$testText = if (Test-Path -LiteralPath $testLog) { Get-Content -Raw -LiteralPath $testLog } else { "" }
[IO.File]::WriteAllText($outputLog, $testText, [Text.UTF8Encoding]::new($false))
$passed = $testExit -eq 0 -and $testText -match '(?m)^PASS:' -and $testText -notmatch '(?m)^(?:SCRIPT ERROR:|.*CrashHandlerException)'
if (-not $passed) {
    if ($testText) { Write-Host $testText.TrimEnd() }
    Write-Host "Preserved failed validation project: $tempProject" -ForegroundColor Yellow
    exit 1
}

Write-Host ($testText -split "`r?`n" | Where-Object { $_ -match '^PASS:' } | Select-Object -Last 1)
Write-Host "Validation log: $outputLog"
Remove-Item -LiteralPath $tempProject -Recurse -Force -ErrorAction SilentlyContinue
if ((Test-Path -LiteralPath $tempBase -PathType Container) -and -not (Get-ChildItem -LiteralPath $tempBase -Force | Select-Object -First 1)) { Remove-Item -LiteralPath $tempBase -Force -ErrorAction SilentlyContinue }
exit 0
