extends SceneTree
## Run in an isolated project containing the addon and docs. Pass -- --write to regenerate.

const OUTPUT := "res://docs/curve_samples.js"
const EXAMPLES := "res://addons/easing_curve/examples/"

func _init() -> void:
	var samples := {}
	for slug in ["popup", "sliding_door", "charge_meter"]:
		var curve := load(EXAMPLES + slug + "_curve.tres") as EasingCurve
		if curve == null:
			quit(1)
			return
		var values: Array[float] = []
		for index in range(257):
			values.append(curve.sample(float(index) / 256.0))
		samples[slug] = values
	var source := "// Generated by test/scripts/docs/export_doc_samples.gd; do not edit.\nwindow.CURVE_SAMPLES = " + JSON.stringify(samples) + ";\n"
	if "--write" in OS.get_cmdline_user_args():
		var file := FileAccess.open(OUTPUT, FileAccess.WRITE)
		if file == null:
			push_error("Could not write " + OUTPUT)
			quit(1)
			return
		file.store_string(source)
	elif FileAccess.get_file_as_string(OUTPUT) != source:
		push_error("Documentation curve samples are stale. Regenerate with -- --write.")
		quit(1)
		return
	print("PASS: documentation samples match the three authored curves")
	quit()
